apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-database.fullname" . }}
  labels:
    {{- include "todo-database.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secrets.POSTGRES_USER | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD | b64enc | quote }}
  POSTGRES_DB: {{ .Values.secrets.POSTGRES_DB | b64enc | quote }}
