apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-backend.fullname" . }}
  labels:
    {{- include "todo-backend.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | b64enc | quote }}
  BETTER_AUTH_SECRET: {{ .Values.secrets.BETTER_AUTH_SECRET | b64enc | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.OPENAI_API_KEY | b64enc | quote }}
